### ISSUE TITLE
Clicking on extension doesn't do anything on copilot

### ISSUE THREAD

**Issue by devinat1** [abstracta/browser-copilot#1]
On version 0.7.4, I installed the extension on chrome and tried to click on the extension, but nothing happened when I clicked on the extension in question.

**Comment by rabelenda** [comment]
Hello, thank you for trying out the extension!

When you install it, you need to open a new tab and load a page on it to display the extension UI. Can you try that and let us know?

We need to implement some changes to make it available to all existing tabs after installation, and need to review if there is any alternative to load the UI when a tab has not loaded HTML.
